//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TUnusedHit_h
#define ND__TTrackerReconModule__TUnusedHit_h
namespace ND {
namespace TTrackerReconModule {
class TUnusedHit;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

namespace ND {
namespace TTrackerReconModule {
class TUnusedHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      TotalCharge;    //Deposited charge (the hit EDeposit)
   TVector3    Position;       //The position of the hit component 0=x 1=y 2=z in mm
   TVector3    Variance;       //The position variance in mm
   double      Time;           //Time of the hit in ns
   double      TimeUnc;        //Time Uncertainty of hit in ns

   TUnusedHit();
   TUnusedHit(TUnusedHit && ) = default;
   TUnusedHit &operator=(const TUnusedHit & );
   TUnusedHit(const TUnusedHit & );
   virtual ~TUnusedHit();

   ClassDef(TUnusedHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
