//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconShower_h
#define ND__TTrackerECALReconModule__TECALReconShower_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconShower;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconShower : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    ConeAngle;    //The shower opening angle.
   TVector3    Direction;    //The shower direction.
   double      EDeposit;     //The energy deposited in the shower
   TLorentzVector Position;     //The shower position.
   TLorentzVector PositionVar;    //The shower position variance.
   TLorentzVector BackPosition;    //The charge weighted position of the end of the shower

   TECALReconShower();
   TECALReconShower(TECALReconShower && ) = default;
   TECALReconShower &operator=(const TECALReconShower & );
   TECALReconShower(const TECALReconShower & );
   virtual ~TECALReconShower();

   ClassDef(TECALReconShower,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
