//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSubBaseShowerObject_h
#define ND__TSubBaseShowerObject_h
namespace ND {
class TSubBaseShowerObject;
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"
#include "TVector3.h"

namespace ND {
class TSubBaseShowerObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Cone;        //The opening angles of the reconstructed shower cone.

   TSubBaseShowerObject();
   TSubBaseShowerObject(TSubBaseShowerObject && ) = default;
   TSubBaseShowerObject &operator=(const TSubBaseShowerObject & );
   TSubBaseShowerObject(const TSubBaseShowerObject & );
   virtual ~TSubBaseShowerObject();

   ClassDef(TSubBaseShowerObject,2); // Generated by MakeProject.
};
} // namespace
#endif
