//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGVertex_h
#define ND__TSFGReconModule__TSFGVertex_h
namespace ND {
namespace TSFGReconModule {
class TSFGVertex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>
#include "TLorentzVector.h"

namespace ND {
namespace TSFGReconModule {
class TSFGVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm which produced this object
   vector<int> Vertices;         //The indices of the vertices contained by the current object.
   vector<int> Particles;        //The indices of the particles contained by the current object.
   vector<int> Tracks;           //The indices of the tracks contained by the current object.
   vector<int> Showers;          //The indices of the showers contained by the current object.
   vector<int> Clusters;         //The indices of the clusters contained by the current object.
   vector<int> Nodes;            //The indices of the nodes contained by the current object.
   vector<int> Hits;             //The indices of the hits contained by the current object.
   int         NHits;            //Number of hits
   unsigned int UniqueId;         //A unique Id used for reconstruction objects.
   int          Status;           //The reported status of the corresponding object.  Use ND::TReconBase::StateBits to check the which status flags are set.
   float        Quality;          //The reported reconstruction 'quality' of the vertex.  Retrieved from ND::TReconBase::GetQuality
   int          NDOF;             //The Number of Degrees of Freedom in the vertex.  Retrieved from ND::TReconBase::GetNDOF
   TLorentzVector Position;         //Position of the correspponding object.
   TLorentzVector PosVariance;      //Variance on the position of the corresponding object.
   vector<int>    Truth_PrimaryTrajIds;    //The vector of primary true trajectory Ids which contribute to the ND::THits which are constituents of this vertex.
   vector<int>    Truth_TrajIds;           //The vector of true trajectory Ids which contribute to the ND::THits which are constituents of this vertex.
   vector<int>    Truth_HitCount;          //The number of THits that each truth trajectory contributed to.
   vector<float>  Truth_ChargeShare;       //The weighted reconstructed charge deposited by each truth

   TSFGVertex();
   TSFGVertex(TSFGVertex && ) = default;
   TSFGVertex &operator=(const TSFGVertex & );
   TSFGVertex(const TSFGVertex & );
   virtual ~TSFGVertex();

   ClassDef(TSFGVertex,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
