//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconCluster_h
#define ND__TTrackerECALReconModule__TECALReconCluster_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconCluster;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconCluster : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //The cluster position.
   TLorentzVector PositionVar;    //The cluster position variance.
   int            NDOF;           //The number of degrees of freedom in the reconstruction.
   double         EDeposit;       //The charge deposited by the cluster.

   TECALReconCluster();
   TECALReconCluster(TECALReconCluster && ) = default;
   TECALReconCluster &operator=(const TECALReconCluster & );
   TECALReconCluster(const TECALReconCluster & );
   virtual ~TECALReconCluster();

   ClassDef(TECALReconCluster,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
