//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TSFGObject_h
#define ND__TGlobalReconModule__TSFGObject_h
namespace ND {
namespace TGlobalReconModule {
class TSFGObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace ND {
namespace TGlobalReconModule {
class TSFGObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Type;        //Object type,  0: Particle, 1: Track, 2: Cluster, 3: Shower, 4: Vertex
   double      avgtime;     //Average fully corrected SFG hit time.
   double      EDeposit;    //Energy deposit of the corresponding object.
   TLorentzVector Position;    //Position of the correspponding object.
   TLorentzVector PosVariance;    //Variance on the position of the corresponding object.
   TVector3       Direction;      //Direction of the corresponding object.
   TVector3       DirVariance;    //Direction variance of the corresponding object.
   double         PIDWeightProt;    //PID weights for proton hypothesis
   double         PIDWeightPion;    //PID weights for pion hypothesis
   double         PIDWeightMuon;    //PID weights for muon hypothesis
   double         PIDWeightElec;    //PID weights for electron hypothesis
   int            ProtonBraggCut;    //Proton Bragg peak cut (only used for SFGD contained tracks)
   int            PionBraggCut;      //Positive Pion Bragg peak cut (only used for SFGD contained tracks)
   int            NegPionBraggCut;    //Negative Bragg peak cut (only used for SFGD contained tracks)
   vector<TLorentzVector> HitPosition;        //Vector to store the position of each hit
   vector<TLorentzVector> HitPosVariance;     //Vector to store the variance of the position of each hit
   vector<double>         HitCharge;          //Vector to store the charge of each hit
   vector<int>            HitTrajID;          //Vector to store the ID of the Trajectory that created the hit
   vector<vector<int> >   HitUniqueID;        //Vector to store the Unique ID of the hit
   vector<TLorentzVector> NodePosition;       //Vector to store the position and time of each node
   vector<TLorentzVector> NodePosVariance;    //Vector to store the variance on the  position and time of each node
   vector<TVector3>       NodeDirection;      //Vector to store the direction of each node
   vector<TVector3>       NodeDirVariance;    //Vector to store the variance on the direction of each node
   vector<double>         NodeEDeposit;       //Vector to store the energy deposit of each node
   vector<double>         NodeEDeposit_fit;    //Fitted node energy deposit
   vector<int>            NodeNHits;           //Vector to store the number of hits contributing to each node
   vector<vector<int> >   NodeHits;            //Vector to store the hits contributing to each node
   vector<vector<int> >   NodeUniqueID;        //Vector to store the Unique ID of the node

   TSFGObject();
   TSFGObject(TSFGObject && ) = default;
   TSFGObject &operator=(const TSFGObject & );
   TSFGObject(const TSFGObject & );
   virtual ~TSFGObject();

   ClassDef(TSFGObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
