//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TSMRDHit_h
#define ND__TGlobalReconModule__TSMRDHit_h
namespace ND {
namespace TGlobalReconModule {
class TSMRDHit;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

namespace ND {
namespace TGlobalReconModule {
class TSMRDHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Wall;        //SMRD wall number, 0=Top, 1=Bottom, 2= Right, 3= Left.
   int         Yoke;        //Yoke ring number.
   int         Layer;       //SMRD hit layer number.
   int         Tower;       //SMRD Tower number.
   int         Counter;     //SMRD scint number.
   double      Charge;      //Deposited charge
   double      Time;        //Hit time [ns]
   TVector3    Position;    //Hit position in global ND coordinates [mm]
   TVector3    PositionError;    //The variance on ND::TGlobalReconModule::TSMRDHit::Position [mm]
   int         Type;             //The hit 'type': (0=X,1=Y,2=Z)

   TSMRDHit();
   TSMRDHit(TSMRDHit && ) = default;
   TSMRDHit &operator=(const TSMRDHit & );
   TSMRDHit(const TSMRDHit & );
   virtual ~TSMRDHit();

   ClassDef(TSMRDHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
