//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TFgdOnlyModule__TFgd2DIsoTrack_h
#define ND__TFgdOnlyModule__TFgd2DIsoTrack_h
namespace ND {
namespace TFgdOnlyModule {
class TFgd2DIsoTrack;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include "TVector3.h"
#include <vector>

namespace ND {
namespace TFgdOnlyModule {
class TFgd2DIsoTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //
   int         NHits;            //
   double      Angle;            //Angle
   double      SumCharge;        //Charge Sum
   double      Range;            //Range
   TLorentzVector Origin;           //Origin
   TLorentzVector OriginVariance;    //Variance on origin
   TVector3       Direction;         //Direection
   vector<TVector3*> HitPositions;      //Hit positions
   int               TrajId;            //Trajectory id`
   double            Completeness;      //Completeness
   double            Cleanliness;       //Cleanlikness

   TFgd2DIsoTrack();
   TFgd2DIsoTrack(TFgd2DIsoTrack && ) = default;
   TFgd2DIsoTrack &operator=(const TFgd2DIsoTrack & );
   TFgd2DIsoTrack(const TFgd2DIsoTrack & );
   virtual ~TFgd2DIsoTrack();

   ClassDef(TFgd2DIsoTrack,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
