//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TSMRDObject_h
#define ND__TGlobalReconModule__TSMRDObject_h
namespace ND {
namespace TGlobalReconModule {
class TSMRDObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"

namespace ND {
namespace TGlobalReconModule {
class TSMRDObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      avgtime;     //Avergaed light-propagation corrected hit time

   TSMRDObject();
   TSMRDObject(TSMRDObject && ) = default;
   TSMRDObject &operator=(const TSMRDObject & );
   TSMRDObject(const TSMRDObject & );
   virtual ~TSMRDObject();

   ClassDef(TSMRDObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
