//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGNode_h
#define ND__TSFGReconModule__TSFGNode_h
namespace ND {
namespace TSFGReconModule {
class TSFGNode;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TSFGReconModule {
class TSFGNode : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<int> Hits;        //Holds internal Ids of Hits pertinent to this reconstruction node.
   float       EDeposit;    //The total reconstructed energy deposit of the corresponding track.
   double      EDeposit_fit;    //Fitted energy deposit for each node
   TLorentzVector Position;        //Position of the corresponding object.
   TLorentzVector PosVariance;     //Variance on the position of the corresponding object.
   TVector3       Direction;       //Direction of the corresponding object.
   TVector3       DirVariance;     //Direction variance of the corresponding object.
   vector<int>    Truth_PrimaryTrajIds;    //Primary Ids of truth trajectories   See the TSFGVertex object for documentation
   vector<int>    Truth_TrajIds;           //True trajectory Ids See the TSFGVertex object for documentation
   vector<int>    Truth_HitCount;          //Nmber of hits contributed by  each  true trajectory See the TSFGVertex object for documentation
   vector<float>  Truth_ChargeShare;       //Carge share o true trajectory  See the TSFGVertex object for documentation

   TSFGNode();
   TSFGNode(TSFGNode && ) = default;
   TSFGNode &operator=(const TSFGNode & );
   TSFGNode(const TSFGNode & );
   virtual ~TSFGNode();

   ClassDef(TSFGNode,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
