//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSubBaseObject_h
#define ND__TSubBaseObject_h
namespace ND {
class TSubBaseObject;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "ND__TTrueParticle.h"

namespace ND {
class TSubBaseObject : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int UniqueID;    //Unique identifier for sub-detector recon objects.
   unsigned long Status;      //The status for the fit.
   int           Detector;    //Integer specifying which subdetector(s) the object belongs to. See TGlobalReconModule::GetDetectorNumber for the options.
   int           NHits;       //The number of constituent hits.
   int           NNodes;      //The number of reconstruction nodes.
   int           NDOF;        //The number of degrees of freedom in the fit.
   double        Chi2;        //The chi2 of the fit.
   double        EDeposit;    //Deposited energy, N.B. the meaning of this is subdetector-local.
   int           NConstituents;    //The number of constituents.
   double        Length;           //The length of the track or shower (RMS)
   TLorentzVector FrontPosition;    //The global coordinate position at the 'front' of the object.
   TLorentzVector BackPosition;     //The global coordinate position at the 'back' of the object.
   TLorentzVector FrontPositionVar;    //The uncertainty on ND::TSubBaseObject::FrontPosition.
   TLorentzVector BackPositionVar;     //The uncertainty on ND::TSubBaseObject::BackPosition.
   TVector3       FrontDirection;      //The direction at the 'front' of the object.
   TVector3       BackDirection;       //The direction at the 'back' of the object.
   TVector3       FrontDirectionVar;    //The uncertainty on ND::TSubBaseObject::FrontDirection.
   TVector3       BackDirectionVar;     //The uncertainty on ND::TSubBaseObject::BackDirection.
   double         FrontMomentum;        //The momentum measurement at the 'front' of the object.
   double         BackMomentum;         //The momentum measurement at the 'back' of the object.
   double         FrontMomentumError;    //The uncertainty on ND::TSubBaseObject::FrontMomentum.
   double         BackMomentumError;     //The uncertainty on ND::TSubBaseObject::BackMomentum.
   ND::TTrueParticle TrueParticle;          //The associated true particle.

   TSubBaseObject();
   TSubBaseObject(TSubBaseObject && ) = default;
   TSubBaseObject &operator=(const TSubBaseObject & );
   TSubBaseObject(const TSubBaseObject & );
   virtual ~TSubBaseObject();

   ClassDef(TSubBaseObject,2); // Generated by MakeProject.
};
} // namespace
#endif
