//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TSfgTimeBin_h
#define ND__TGlobalReconModule__TSfgTimeBin_h
namespace ND {
namespace TGlobalReconModule {
class TSfgTimeBin;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"
#include "ND__TGlobalReconModule__TOutermostHits.h"
#include "Riostream.h"
#include <vector>
#include "TClonesArray.h"
#include "ND__TGlobalReconModule__TGlobalHit.h"

namespace ND {
namespace TGlobalReconModule {
class TSfgTimeBin : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      minTime;     //Bin start time.
   double      maxTime;     //Bin end time.
   double      rawChargeSum;    //Summed hit charge in SFG
   TVector3    chargeWeightedPos;    //\brief Charge weighted average hit position in SFG
   ND::TGlobalReconModule::TOutermostHits SFGOutermostHits;     //A named collection of the outermost hits in X,Y, and Z from SFG
   int                                    nHits;                //Number of hits in SFG
   vector<float>                          SFGHitPositionX;      //Vector to store the Xposition of each hit in SFG
   vector<float>                          SFGHitPositionY;      //Vector to store the  Y position of each hit in SFG
   vector<float>                          SFGHitPositionZ;      //Vector to store the X or Y position of each hit in SFG
   vector<float>                          SFGHitQ;              //Vector to store the charge of each hit in SFG
   vector<float>                          SFGHitT;              //Vector to store the time of each hit in SFG
   vector<int>                            SFGHitTrajID;         //Vector to store the ID of the Trajectory that created the hit in SFG
   int                                    NSFGUnused;           //Number of hits unused in SFG
   TClonesArray*                          SFGUnused;            //The vector unused hits in SFG
   ND::TGlobalReconModule::TGlobalHit     hackSFGUnused;        //This is just here to fool TFile::MakeProject, not a real object.
   int                                    g4ID;                 //The ID for the G4 trajectory that contributed most to this time bin.

   TSfgTimeBin();
   TSfgTimeBin(TSfgTimeBin && ) = default;
   TSfgTimeBin &operator=(const TSfgTimeBin & );
   TSfgTimeBin(const TSfgTimeBin & );
   virtual ~TSfgTimeBin();

   ClassDef(TSfgTimeBin,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
