//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__THATObject_h
#define ND__TGlobalReconModule__THATObject_h
namespace ND {
namespace TGlobalReconModule {
class THATObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"

namespace ND {
namespace TGlobalReconModule {
class THATObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Length;      //HAT segment length (calculated with the sum of neighboring node distances)
   double      LengthYZ;    //HAT segment length (same as above but projected on YZ plane)
   double      Charge;      //Charge from the HAT pid (+1, or -1)
   double      TrackCharge;    //Track charge computed as in hatReconTreeMaker
   double      TrackMomentum;    //Track momentum computed as in hatReconTreeMaker
   double      TrackDirection[3];    //Track direction computed as in hatReconTreeMaker
   double      TrackPosition[3];     //Track position computed as in hatReconTreeMaker
   double      Momentum_L;           //P measured for the low Z half of Endplate part of the track (P_L)
   double      Momentum_R;           //P measured for the high Z half of Endplate part of the track (P_R)
   double      Momentum_D;           //P measured for the low Y half of Endplate part of the track (P_D)
   double      Momentum_U;           //P measured for the high Y half of Endplate part of the track (P_U)
   double      Momentum_No_ExBDist;    //P estimation w/o accounting for E nor B distortions
   double      Momentum_No_ExBDist_L;    //P_L estimation w/o accounting for E nor B distortions
   double      Momentum_No_ExBDist_R;    //P_R estimation w/o accounting for E nor B distortions
   double      Momentum_No_ExBDist_D;    //P_D estimation w/o accounting for E nor B distortions
   double      Momentum_No_ExBDist_U;    //P_U estimation w/o accounting for E nor B distortions
   int         Ncl;                      //Number of robust clusters
   double      dEdx_WF;                  //Corrected dE/dx calculated using the waveform method
   double      dEdx_XP;                  //dE/dx calculated using the crossed pads method
   double      mom;                      //Reconstructed momentum from HAT
   double      PullEle;                  //Pull for HAT pid electron hypothesis
   double      PullMuon;                 //Pull for HAT pid muon hypothesis
   double      PullPion;                 //Pull for HAT pid pion hypothesis
   double      PullKaon;                 //Pull for HAT pid kaon hypothesis
   double      PullProton;               //Pull for HAT pid proton hypothesis
   double      dEdxexpEle;               //Estimated dE/dx for electron hypothesis
   double      dEdxexpMuon;              //Estimated dE/dx for muon hypothesis
   double      dEdxexpPion;              //Estimated dE/dx for pion hypothesis
   double      dEdxexpKaon;              //Estimated dE/dx for kaon hypothesis
   double      dEdxexpProton;            //Estimated dE/dx for proton hypothesis
   double      SigmaEle;                 //Sigma estimated width of HAT pid electron hypothesis
   double      SigmaMuon;                //Sigma estimated width of HAT pid muon hypothesis
   double      SigmaPion;                //Sigma estimated width of HAT pid pion hypothesis
   double      SigmaKaon;                //Sigma estimated width of HAT pid kaon hypothesis
   double      SigmaProton;              //Sigma estimated width of HAT pid proton hypothesis
   int         T0type;                   //
   double      TrueEDeposit;             //True energy deposition summing over hit segments
   double      TrueEDeposit_sec;         //The same, but use function GetSecondaryDeposition()
   double      TruedEdx;                 //True dE/dx computed based on hit segment energy deposition and "length"
   double      TruedEdx_sec;             //The same, but use function GetSecondaryDeposition()

   THATObject();
   THATObject(THATObject && ) = default;
   THATObject &operator=(const THATObject & );
   THATObject(const THATObject & );
   virtual ~THATObject();

   ClassDef(THATObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
