//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGAlgoRes_h
#define ND__TSFGReconModule__TSFGAlgoRes_h
namespace ND {
namespace TSFGReconModule {
class TSFGAlgoRes;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace ND {
namespace TSFGReconModule {
class TSFGAlgoRes : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm that generated this object.
   vector<int> Vertices;         //Holds index of the TSFGVertex objects that are pertinent to this algorithm result.
   vector<int> Particles;        //Holds index of the TSFGParticle objects that are pertinent to this algorithm result.
   vector<int> Tracks;           //Holds index of the TSFGTrack objects that are pertinent to this  algorithm result.
   vector<int> Showers;          //Holds index of the TSFGShower objects that are pertinent to this algorithm result.
   vector<int> Clusters;         //Holds index of the TSFGCluster objects that are pertinent to this algorithm result.
   vector<int> Nodes;            //Holds index of the TSFGNode objects that are pertinent to this algorithm result.
   vector<int> Hits;             //Holds index of the TSFGHit objects that are pertinent to this algorithm result.
   int         NHits;            //A count of the Hits associated with this object.
   unsigned int UniqueId;         //A unique Id used for reconstruction objects
   string       FullName;         //The path to the result inside the event.  This is also the string
   vector<int>  AlgoResults;      //The index of the daughter algorithms for this algorithm result.
   int          Parent;           //The index of the parent algorithm for this algorithm result.  This will be -1 if this doesn't have a parent.
   int          UsedHitCluster;    //The index of the cluster that contains all of the hits used by this algorithm result.  This is -1 if the hits are not saved.
   int          UnusedHitCluster;    //The index of the cluster that contains all of the hits not used by this algorithm result.  This is -1 if the hits are not saved.

   TSFGAlgoRes();
   TSFGAlgoRes(TSFGAlgoRes && ) = default;
   TSFGAlgoRes &operator=(const TSFGAlgoRes & );
   TSFGAlgoRes(const TSFGAlgoRes & );
   virtual ~TSFGAlgoRes();

   ClassDef(TSFGAlgoRes,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
