//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGShower_h
#define ND__TSFGReconModule__TSFGShower_h
namespace ND {
namespace TSFGReconModule {
class TSFGShower;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TSFGReconModule {
class TSFGShower : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm which produced this object
   vector<int> Vertices;         //The indices of the vertices contained by the current object.
   vector<int> Particles;        //The indices of the particles contained by the current object.
   vector<int> Tracks;           //The indices of the tracks contained by the current object.
   vector<int> Showers;          //The indices of the showers contained by the current object.
   vector<int> Clusters;         //The indices of the clusters contained by the current object.
   vector<int> Nodes;            //The indices of the nodes contained by the current object.
   vector<int> Hits;             //The indices of the hits contained by the current object.
   int         NHits;            //Number of hits
   unsigned int UniqueId;         //A unique Id used for reconstruction objects.
   int          Status;           //The reported Status of the corresponding object.  Use ND::TReconBase::StateBits to check the which status flags are set.
   float        Quality;          //The reported reconstruction 'quality' of the corresponding object.  Uses ND::TReconBase::GetQuality
   int          NDOF;             //The Number of Degrees of Freedom in the reconstruction of the corresponding object.  Retrieved from ND::TReconBase::GetNDOF
   float        EDeposit;         //The total reconstructed energy deposit of the corresponding track. This is usually just the sum of the charge for all of the hits.
   TLorentzVector Position;         //Position of the corresponding object.
   TLorentzVector PosVariance;      //Variance on the position of the corresponding object.
   TVector3       Direction;        //Direction of the corresponding object.
   TVector3       DirVariance;      //Direction variance of the corresponding object.
   int            TrueParticleID;    //True Geant4 particle associated to a TSFGTrack
   int            TrueParticlePur;    //Purity of Geant4 particle associated to a TSFGTrack
   int            TrueParticleEff;    //Efficiency of Geant4 particle associated to a TSFGTrack
   float          Cone;               //The opening angle of the TShowerState cone of the corresponding TReconShower.
   float          Width;              //The 'width' of the shower, the extent perpendicular to the  direction.
   float          Length;             //The RMS length of the shower, the extent parallel to the direction.
   vector<int>    Truth_PrimaryTrajIds;    //Primary Ids of truth trajectories
   vector<int>    Truth_TrajIds;           //True trajectory Ids
   vector<int>    Truth_HitCount;          //Nmber of hits contributed by  each  true trajectory
   vector<float>  Truth_ChargeShare;       //Carge share o true trajectory

   TSFGShower();
   TSFGShower(TSFGShower && ) = default;
   TSFGShower &operator=(const TSFGShower & );
   TSFGShower(const TSFGShower & );
   virtual ~TSFGShower();

   ClassDef(TSFGShower,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
