//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTOFReconModule__TTOFSingleHit_h
#define ND__TTOFReconModule__TTOFSingleHit_h
namespace ND {
namespace TTOFReconModule {
class TTOFSingleHit;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

namespace ND {
namespace TTOFReconModule {
class TTOFSingleHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int GeomID;      //Geometry Id of the THit.
   unsigned int ChanID;      //Channel Id of the THit.
   float        Integral;    //------ NOTE: Change to getIntegral check with output of tofrecon/
   float        Time;        //Reconstructed hit time from the corresponding TSingleHit.
   TVector3     Position;    //
   int          Feb;         //Front end board module of the THit.
   int          Sampic;      //SAMPIC of the THit
   int          SampicChannel;    //SAMPIC channel of the THit
   float        Cell0Time;        //
   float        TOT;              //
   int          Module;           //
   int          Bar;              //
   int          Sensor;           //

   TTOFSingleHit();
   TTOFSingleHit(TTOFSingleHit && ) = default;
   TTOFSingleHit &operator=(const TTOFSingleHit & );
   TTOFSingleHit(const TTOFSingleHit & );
   virtual ~TTOFSingleHit();

   ClassDef(TTOFSingleHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
