//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALReconModule__TECALReconTrack_h
#define ND__TTrackerECALReconModule__TECALReconTrack_h
namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"
#include "TLorentzVector.h"

namespace ND {
namespace TTrackerECALReconModule {
class TECALReconTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TVector3    Direction;    //The track direction
   double      EDeposit;     //The charge deposited by the track in units of MIPs
   TLorentzVector Position;     //The track starting 4-position.
   TLorentzVector PositionVar;    //The track starting 4-position variance.
   TLorentzVector BackPosition;    //The position of the end of the track

   TECALReconTrack();
   TECALReconTrack(TECALReconTrack && ) = default;
   TECALReconTrack &operator=(const TECALReconTrack & );
   TECALReconTrack(const TECALReconTrack & );
   virtual ~TECALReconTrack();

   ClassDef(TECALReconTrack,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
