//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TTrackerVertex_h
#define ND__TTrackerReconModule__TTrackerVertex_h
namespace ND {
namespace TTrackerReconModule {
class TTrackerVertex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>

namespace ND {
namespace TTrackerReconModule {
class TTrackerVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm that created this object.
   int         Status;           //The status for the fit.
   double      Quality;          //The quality of the fit. Ie. the Prob(chi2,ndof)
   int         NDOF;             //The number of degrees of freedom.

   TTrackerVertex();
   TTrackerVertex(TTrackerVertex && ) = default;
   TTrackerVertex &operator=(const TTrackerVertex & );
   TTrackerVertex(const TTrackerVertex & );
   virtual ~TTrackerVertex();

   ClassDef(TTrackerVertex,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
