//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSHAHashValue_h
#define ND__TSHAHashValue_h
namespace ND {
class TSHAHashValue;
} // end of namespace.

#include "Rtypes.h"

namespace ND {
class TSHAHashValue {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fHash[5];    //

   TSHAHashValue();
   TSHAHashValue(TSHAHashValue && ) = default;
   TSHAHashValue &operator=(const TSHAHashValue & );
   TSHAHashValue(const TSHAHashValue & );
   virtual ~TSHAHashValue();

};
} // namespace
#endif
