//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TData_h
#define ND__TData_h
namespace ND {
class TData;
} // end of namespace.

#include "Rtypes.h"
#include "ND__TDatum.h"

namespace ND {
class TData : public ND::TDatum {

public:
// Nested classes declaration.

public:
// Data Members.

   TData();
   TData(TData && ) = default;
   TData &operator=(const TData & );
   TData(const TData & );
   virtual ~TData();

   ClassDef(TData,4); // Generated by MakeProject.
};
} // namespace
#endif
