//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTruthTrajectoriesModule__TTruthTrajectory_h
#define ND__TTruthTrajectoriesModule__TTruthTrajectory_h
namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectory;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include <vector>
#include "ND__TTruthTrajectoriesModule__TTruthTrajectoryPoint.h"
#include "TVector3.h"

namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectory : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ID;          //
   int         PDG;         //
   std::string      Name;        //
   int         Category;    //
   TLorentzVector InitMomentum;    //
   TLorentzVector InitPosition;    //
   TLorentzVector FinalPosition;    //
   int            ParentID;         //
   int            PrimaryID;        //
   double         Mass;             //
   int            Charge;           //
   std::vector<ND::TTruthTrajectoriesModule::TTruthTrajectoryPoint> Points;           //The trajectory points where interactions occured along the  trajectory.
   std::vector<int>                                                 TraceSubdetectors;    //\brief Vector of integer subdetector codes indicating which subdetectors the particle travelled through.
   std::vector<bool>                                                TraceInActive;        //\brief Vector of booleans indicating whether the particle went through an active part of the corresponding subdetector.
   std::vector<TLorentzVector>                                      TraceEntrancePosition;    //\brief Vector of TLorentzVectors that stores the entrance position of the particle in each subdetector it encounters.
   std::vector<TLorentzVector>                                      TraceExitPosition;        //\brief Vector of TLorentzVectors that stores the exit position of the particle in each subdetector it encounters.
   std::vector<TVector3>                                            TraceEntranceMomentum;    //\brief Vector of TVector3s that stores the entrance momentum of the particle in each subdetector it encounters.
   std::vector<TVector3>                                            TraceExitMomentum;        //\brief Vector of TVector3s that stores the exit momentum of the particle in each subdetector it encounters.

   TTruthTrajectory();
   TTruthTrajectory(TTruthTrajectory && ) = default;
   TTruthTrajectory &operator=(const TTruthTrajectory & );
   TTruthTrajectory(const TTruthTrajectory & );
   virtual ~TTruthTrajectory();

   ClassDef(TTruthTrajectory,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
