//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TVertexConstituent_h
#define ND__TGlobalReconModule__TVertexConstituent_h
namespace ND {
namespace TGlobalReconModule {
class TVertexConstituent;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"

namespace ND {
namespace TGlobalReconModule {
class TVertexConstituent : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Charge;      //Charge of the constituent track
   double      Quality;     //Quality (chi2) of the constituent track
   TVector3    Momentum;    //3-momentum of the constituent track
   int         PID;         //The TGlobalPID of the constituent track

   TVertexConstituent();
   TVertexConstituent(TVertexConstituent && ) = default;
   TVertexConstituent &operator=(const TVertexConstituent & );
   TVertexConstituent(const TVertexConstituent & );
   virtual ~TVertexConstituent();

   ClassDef(TVertexConstituent,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
