//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TTPCOtherObject_h
#define ND__TGlobalReconModule__TTPCOtherObject_h
namespace ND {
namespace TGlobalReconModule {
class TTPCOtherObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"
#include "ND__TTrueParticle.h"

namespace ND {
namespace TGlobalReconModule {
class TTPCOtherObject : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //Charge
   int         Detector;    //Detector
   int         NHits;       //Number of hits
   double      Chi2;        //Chi squared
   double      EDeposit;    //Energy deposit
   TLorentzVector FrontPosition;    //The Front position of the object.
   TLorentzVector BackPosition;     //The Back position of the object.
   TVector3       FrontDirection;    //The Front direction of the object.
   TVector3       BackDirection;     //The Back direction of the object.
   double         Momentum;          //the momentum of the object
   ND::TTrueParticle TrueParticle;      //The true particle

   TTPCOtherObject();
   TTPCOtherObject(TTPCOtherObject && ) = default;
   TTPCOtherObject &operator=(const TTPCOtherObject & );
   TTPCOtherObject(const TTPCOtherObject & );
   virtual ~TTPCOtherObject();

   ClassDef(TTPCOtherObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
