//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DECALReconModule__TP0DECALLayerCharge_h
#define ND__TP0DECALReconModule__TP0DECALLayerCharge_h
namespace ND {
namespace TP0DECALReconModule {
class TP0DECALLayerCharge;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include <TString.h>

namespace ND {
namespace TP0DECALReconModule {
class TP0DECALLayerCharge : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      FirstTime;    //The earliest hit time of the relevant cluster.
   double      LastTime;     //The latest hit time of the relevant cluster.
   double      Charge[6];    //The total charge deposited in each of 6layers. Index 0  corresponds the innermost layer
   TString     module_name;    //The name of the module.

   TP0DECALLayerCharge();
   TP0DECALLayerCharge(TP0DECALLayerCharge && ) = default;
   TP0DECALLayerCharge &operator=(const TP0DECALLayerCharge & );
   TP0DECALLayerCharge(const TP0DECALLayerCharge & );
   virtual ~TP0DECALLayerCharge();

   ClassDef(TP0DECALLayerCharge,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
