//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TTrackerNode_h
#define ND__TTrackerReconModule__TTrackerNode_h
namespace ND {
namespace TTrackerReconModule {
class TTrackerNode;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TTrackerReconModule {
class TTrackerNode : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //The Charge (+-1)
   double      EDeposit;    //The Energy Deposit (number of pe's)
   TLorentzVector Position;    //Position 4-vector (at node) x,y,z,t in mm, ns
   TLorentzVector Variance;    //Position variance 4-vector (at node)var(x),var(y),var(z),var(t) in mm^2, ns^2
   TVector3       Direction;    //Direction vector (at node)
   TVector3       DirectionVariance;    //Direction variance vector (at node)
   double         Momentum;             //Track Momentum (at node) in MeV/c
   double         MomentumError;        //Track Momentum uncertainty (at node) in MeV/c

   TTrackerNode();
   TTrackerNode(TTrackerNode && ) = default;
   TTrackerNode &operator=(const TTrackerNode & );
   TTrackerNode(const TTrackerNode & );
   virtual ~TTrackerNode();

   ClassDef(TTrackerNode,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
