//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGeometrySummaryModule__TTPCMicroMegasVolumes_h
#define ND__TGeometrySummaryModule__TTPCMicroMegasVolumes_h
namespace ND {
namespace TGeometrySummaryModule {
class TTPCMicroMegasVolumes;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <map>
#include <utility>
#include "TGeoNode.h"

namespace ND {
namespace TGeometrySummaryModule {
class TTPCMicroMegasVolumes : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   std::map<int,std::pair<int,const TGeoNode*> > MMvolumes;    // (pair<int,pair<int,const TGeoNode*> >)

   TTPCMicroMegasVolumes();
   TTPCMicroMegasVolumes(TTPCMicroMegasVolumes && ) = default;
   TTPCMicroMegasVolumes &operator=(const TTPCMicroMegasVolumes & );
   TTPCMicroMegasVolumes(const TTPCMicroMegasVolumes & );
   virtual ~TTPCMicroMegasVolumes();

   ClassDef(TTPCMicroMegasVolumes,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
