//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TND280Event_h
#define ND__TND280Event_h
namespace ND {
class TND280Event;
} // end of namespace.

#include "Rtypes.h"
#include "ND__TDataVector.h"
#include "ND__TND280Context.h"
#include "ND__TSHAHashValue.h"
#include "ND__TAlignmentId.h"
#include "ND__TND280Event.h"

namespace ND {
class TND280Event : public ND::TDataVector {

public:
// Nested classes forward declaration.
class Header;

public:
// Nested classes declaration.
class Header {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fRecordType;    //
   unsigned int fTimeStamp;     //
   unsigned int fRunType;       //
   unsigned int fErrorCode;     //
   ULong64_t    fTriggerWord;    //
   unsigned int fMCMSecond;      //
   unsigned int fMCMSubSecond;    //
   unsigned int fMCMTimeSinceBusy;    //
   unsigned int fP0DSecond;           //
   unsigned int fP0DSubSecond;        //
   unsigned int fP0DTimeSinceBusy;    //
   unsigned int fTPCSecond;           //
   unsigned int fTPCSubSecond;        //
   unsigned int fTPCTimeSinceBusy;    //
   unsigned int fHATSecond;           //
   unsigned int fHATSubSecond;        //
   unsigned int fHATTimeSinceBusy;    //
   unsigned int fFGDSecond;           //
   unsigned int fFGDSubSecond;        //
   unsigned int fFGDTimeSinceBusy;    //
   unsigned int fECalSecond;          //
   unsigned int fECalSubSecond;       //
   unsigned int fECalTimeSinceBusy;    //
   unsigned int fSMRDSecond;           //
   unsigned int fSMRDSubSecond;        //
   unsigned int fSMRDTimeSinceBusy;    //
   unsigned int fINGRIDSecond;         //
   unsigned int fINGRIDSubSecond;      //
   unsigned int fINGRIDTimeSinceBusy;    //
   ULong64_t    fCTMTriggerPattern[3];    //
   ULong64_t    fFGDCTMTriggerPattern[3];    //

   Header();
   Header(Header && ) = default;
   Header &operator=(const Header & );
   Header(const Header & );
   virtual ~Header();

   ClassDef(Header,4); // Generated by MakeProject.
};

public:
// Data Members.
   ND::TND280Context fContext;    //
   ND::TSHAHashValue fGeometryHash;    //
   ND::TAlignmentId  fAlignmentId;     //
   ND::TND280Event::Header fHeader;          //

   TND280Event();
   TND280Event(TND280Event && ) = default;
   TND280Event &operator=(const TND280Event & );
   TND280Event(const TND280Event & );
   virtual ~TND280Event();

   ClassDef(TND280Event,9); // Generated by MakeProject.
};
} // namespace
#endif
