//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGParticle_h
#define ND__TSFGReconModule__TSFGParticle_h
namespace ND {
namespace TSFGReconModule {
class TSFGParticle;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TSFGReconModule {
class TSFGParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm which produced this object
   vector<int> Vertices;         //The indices of the vertices contained by the current object.
   vector<int> Particles;        //The indices of the particles contained by the current object.
   vector<int> Tracks;           //The indices of the tracks contained by the current object.
   vector<int> Showers;          //The indices of the showers contained by the current object.
   vector<int> Clusters;         //The indices of the clusters contained by the current object.
   vector<int> Nodes;            //The indices of the nodes contained by the current object.
   vector<int> Hits;             //The indices of the hits contained by the current object.
   int         NHits;            //Number of hits
   unsigned int UniqueId;         //A unique Id used for reconstruction objects.
   int          Status;           //The reported Status of the corresponding ND::TReconPID.  Use
   float        Quality;          //The reported reconstruction 'quality' of the corresponding
   int          NDOF;             //The Number of Degrees of Freedom in the reconstruction of the
   TLorentzVector Position;         //Position of the correspponding object.
   TLorentzVector PosVariance;      //Variance on the position of the corresponding object.
   TVector3       Direction;        //Direction of the corresponding object.
   TVector3       DirVariance;      //Direction variance of the corresponding object.
   float          Momentum;         //The reconstructed momentum of the corresponding TReconPID.
   float          Charge;           //The reconstructed particle charge of the corresponding TReconPID.
   vector<int>    PID;              //Potential PIDs (ND::TReconPID::ParticleId) matching with TSFGParticle::PID_Weight values.
   vector<float>  PID_weight;       //PID weights for each PID in TSFGParticle::PID.
   int            TrueParticleID;    //True G4 particle associated to a TSFGParticle
   int            TrueParticlePur;    //Purity of the True G4 particle associated to a TSFGParticle
   int            TrueParticleEff;    //Efficiency of the True G4 particle associated to a TSFGParticle
   vector<int>    Truth_PrimaryTrajIds;    //Primary Ids of truth trajectories
   vector<int>    Truth_TrajIds;           //True trajectory Ids
   vector<int>    Truth_HitCount;          //Nmber of hits contributed by  each  true trajectory
   vector<float>  Truth_ChargeShare;       //Carge share o true trajectory

   TSFGParticle();
   TSFGParticle(TSFGParticle && ) = default;
   TSFGParticle &operator=(const TSFGParticle & );
   TSFGParticle(const TSFGParticle & );
   virtual ~TSFGParticle();

   ClassDef(TSFGParticle,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
