//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TFgdOnlyModule__TFgd3DShowerHyp_h
#define ND__TFgdOnlyModule__TFgd3DShowerHyp_h
namespace ND {
namespace TFgdOnlyModule {
class TFgd3DShowerHyp;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

namespace ND {
namespace TFgdOnlyModule {
class TFgd3DShowerHyp : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //Identified start position of the shower.
   TLorentzVector PositionVar;    //Variance on the start position of the shower.
   TVector3       Direction;      //Identified direction of the shower, found using PCA.
   TVector3       DirectionVar;    //Variance on the direction of the shower.
   TVector3       ConeAngle;       //Opening angle of the cone describing this shower.
   TVector3       ConeAngleVar;    //Variance on the cone opening angle.
   double         EDeposit;        //Energy deposited in this shower.
   TVector3       QAvgInThirds;    //Charge of hits in 1st, 2nd and 3rd groups, based
   TVector3       SpreadInThirds;    //Average transverse spread of hits  in the 1st,

   TFgd3DShowerHyp();
   TFgd3DShowerHyp(TFgd3DShowerHyp && ) = default;
   TFgd3DShowerHyp &operator=(const TFgd3DShowerHyp & );
   TFgd3DShowerHyp(const TFgd3DShowerHyp & );
   virtual ~TFgd3DShowerHyp();

   ClassDef(TFgd3DShowerHyp,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
