//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TOutermostHits_h
#define ND__TGlobalReconModule__TOutermostHits_h
namespace ND {
namespace TGlobalReconModule {
class TOutermostHits;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "ND__TGlobalReconModule__TGlobalHit.h"

namespace ND {
namespace TGlobalReconModule {
class TOutermostHits : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   ND::TGlobalReconModule::TGlobalHit hitMinX;     //Hit with lowest X position.
   ND::TGlobalReconModule::TGlobalHit hitMaxX;     //Hit with highest X position.
   ND::TGlobalReconModule::TGlobalHit hitMinY;     //Hit with lowest Y position.
   ND::TGlobalReconModule::TGlobalHit hitMaxY;     //Hit with highest Y position.
   ND::TGlobalReconModule::TGlobalHit hitMinZ;     //Hit with lowest Z position.
   ND::TGlobalReconModule::TGlobalHit hitMaxZ;     //Hit with highest Z position.

   TOutermostHits();
   TOutermostHits(TOutermostHits && ) = default;
   TOutermostHits &operator=(const TOutermostHits & );
   TOutermostHits(const TOutermostHits & );
   virtual ~TOutermostHits();

   ClassDef(TOutermostHits,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
