//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TTPCObject_h
#define ND__TGlobalReconModule__TTPCObject_h
namespace ND {
namespace TGlobalReconModule {
class TTPCObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"
#include "Riostream.h"
#include <vector>

namespace ND {
namespace TGlobalReconModule {
class TTPCObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //Charge from the TPC pid (+1, or -1)
   double      NTrun;       //70% of the number of cluster
   double      Craw;        //Raw mean charge deposit in PID
   double      Ccorr;       //Corrected truncated mean charge deposit in PID
   double      PullEle;     //Pull for TPC pid electron hypothesis
   double      PullMuon;    //Pull for TPC pid muon hypothesis
   double      PullPion;    //Pull for TPC pid pion hypothesis
   double      PullKaon;    //Pull for TPC pid kaon hypothesis
   double      PullProton;    //Pull for TPC pid proton hypothesis
   double      dEdxexpEle;    //Estimated dE/dx for electron hypothesis
   double      dEdxexpMuon;    //Estimated dE/dx for muon hypothesis
   double      dEdxexpPion;    //Estimated dE/dx for pion hypothesis
   double      dEdxexpKaon;    //Estimated dE/dx for kaon hypothesis
   double      dEdxexpProton;    //Estimated dE/dx for proton hypothesis
   double      SigmaEle;         //Sigma estimated width of TPC pid electron hypothesis
   double      SigmaMuon;        //Sigma estimated width of TPC pid muon hypothesis
   double      SigmaPion;        //Sigma estimated width of TPC pid pion hypothesis
   double      SigmaKaon;        //Sigma estimated width of TPC pid kaon hypothesis
   double      SigmaProton;      //Sigma estimated width of TPC pid proton hypothesis
   vector<int> T0Source;         //The T0Source, the values are defined in TTPCFitStatusBranch.hxx, the TTPCT0Source enumeration.
   vector<int> NHorRows;         //The number of horizontal clusters in the track
   vector<int> NVerRows;         //The number of vertical clusters in the track
   int         NbFittedVerticalClusters;    //The number of vertical clusters contributed to the fit,  TREx
   int         NbFittedHorizontalClusters;    //The number of horizontal clusters contributed to the fit,  TREx
   double      PDist;                         //Placeholder for momentum of BField refit.
   double      PEField;                       //Placeholder for momentum of EField refit.
   double      TPCLength;                     //TPC track length.
   int         TrackType;                     //Record of why the track was refit with a kalman filter fit instead of the likelihood fit.
   double      TrueEDeposit;                  //True energy deposition summing over hit segments
   double      TrueEDeposit_sec;              //The same, but use function GetSecondaryDeposition()
   double      TruedEdx;                      //True dE/dx computed based on hit segment energy deposition and "length"
   double      TruedEdx_sec;                  //The same, but use function GetSecondaryDeposition()

   TTPCObject();
   TTPCObject(TTPCObject && ) = default;
   TTPCObject &operator=(const TTPCObject & );
   TTPCObject(const TTPCObject & );
   virtual ~TTPCObject();

   ClassDef(TTPCObject,4); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
