//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TP0DReconModule__TP0DHit_h
#define ND__TP0DReconModule__TP0DHit_h
namespace ND {
namespace TP0DReconModule {
class TP0DHit;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"

namespace ND {
namespace TP0DReconModule {
class TP0DHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int GeomID;      //Geometry Id of the TSingleHit.
   unsigned int ChanID;      //Channel Id of the TSingleHit.
   float        Charge;      //Reconstructed hit charge without attenuation correction from the  corresponding TSingleHit.
   float        Time;        //Reconstructed hit time from the corresponding TSingleHit.

   TP0DHit();
   TP0DHit(TP0DHit && ) = default;
   TP0DHit &operator=(const TP0DHit & );
   TP0DHit(const TP0DHit & );
   virtual ~TP0DHit();

   ClassDef(TP0DHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
