//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TFgdOnlyModule__TFgd3DIsoTrack_h
#define ND__TFgdOnlyModule__TFgd3DIsoTrack_h
namespace ND {
namespace TFgdOnlyModule {
class TFgd3DIsoTrack;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include "TVector3.h"
#include <vector>

namespace ND {
namespace TFgdOnlyModule {
class TFgd3DIsoTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //Algorithm name
   int         NHits;            //Number of hits
   double      SumCharge;        //Sum of charge
   double      Range;            //Range
   TLorentzVector Origin;           //Origin
   TLorentzVector OriginVariance;    //Variance on origin
   TVector3       Direction;         //Direection
   double         muonPull;          //Muon pull
   double         pionPull;          //Pion pull
   double         protonPull;        //Proton pull
   vector<TVector3*> XZHitPositions;    //XZ Hit Positions
   vector<TVector3*> YZHitPositions;    //YZ Hit Positions
   int               TrajId;            //Trajectory id`
   double            Completeness;      //Completeness
   double            Cleanliness;       //Cleanlikness

   TFgd3DIsoTrack();
   TFgd3DIsoTrack(TFgd3DIsoTrack && ) = default;
   TFgd3DIsoTrack &operator=(const TFgd3DIsoTrack & );
   TFgd3DIsoTrack(const TFgd3DIsoTrack & );
   virtual ~TFgd3DIsoTrack();

   ClassDef(TFgd3DIsoTrack,3); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
