//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTruthTrajectoriesModule__TTruthTrajectoryPoint_h
#define ND__TTruthTrajectoriesModule__TTruthTrajectoryPoint_h
namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectoryPoint;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"

namespace ND {
namespace TTruthTrajectoriesModule {
class TTruthTrajectoryPoint : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ProcessType;    //The process type that caused the Monte Carlo to generate this  point.
   float       PositionX;      //The X position of the trajectory point [mm].
   float       PositionY;      //The Y position of the trajectory point [mm].
   float       PositionZ;      //The Z position of the trajectory point [mm].
   float       PositionT;      //The time of the trajectory point [ns].
   float       MomentumX;      //The X momentum of the particle leaving the trajectory point [MeV].
   float       MomentumY;      //The Y momentum of the particle leaving the trajectory point [MeV].
   float       MomentumZ;      //The Z position of the particle leaving the trajectory point [MeV].

   TTruthTrajectoryPoint();
   TTruthTrajectoryPoint(TTruthTrajectoryPoint && ) = default;
   TTruthTrajectoryPoint &operator=(const TTruthTrajectoryPoint & );
   TTruthTrajectoryPoint(const TTruthTrajectoryPoint & );
   virtual ~TTruthTrajectoryPoint();

   ClassDef(TTruthTrajectoryPoint,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
