//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TGlobalPID_h
#define ND__TGlobalReconModule__TGlobalPID_h
namespace ND {
namespace TGlobalReconModule {
class TGlobalPID;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include <string>
#include "TVector3.h"
#include "TLorentzVector.h"
#include <utility>
#include "TVector2.h"
#include "TClonesArray.h"
#include "ND__TTrueParticle.h"
namespace std {} using namespace std;
#include "ND__TGlobalReconModule__TTPCObject.h"
#include "ND__TGlobalReconModule__THATObject.h"
#include "ND__TGlobalReconModule__TFGDObject.h"
#include "ND__TGlobalReconModule__TSFGObject.h"
#include "ND__TGlobalReconModule__TTOFObject.h"
#include "ND__TGlobalReconModule__TECALObject.h"
#include "ND__TGlobalReconModule__TP0DObject.h"
#include "ND__TGlobalReconModule__TSMRDObject.h"
#include "ND__TGlobalReconModule__TTrackerObject.h"
#include "ND__TGlobalReconModule__TGlobalPIDAlternate.h"

namespace ND {
namespace TGlobalReconModule {
class TGlobalPID : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int UniqueID;    //Unique identifier for global recon objects (needed fro broken association)
   vector<unsigned int> BrokenUniqueIDs;    //Broken partners unique IDs
   string               AlgorithmName;      //Name of the algorithm that created this object.
   unsigned long        Detectors;          //Detectors used
   bool                 DetectorUsed[23];    //Detectors used. Index order from 0 to 26
   unsigned long        Status;              //Status for the fit.
   int                  NDOF;                //Number of degrees of freedom.
   double               Chi2;                //Chi squared of the fit.
   int                  NNodes;              //Number of nodes.
   int                  NHits;               //Number of hits.
   int                  NConstituents;       //Number of constituents.
   bool                 isForward;           //Sense of object.
   bool                 SenseOK;             //Sense of object.
   bool                 IsCurvBack;          //A curving-back object
   bool                 IsFgdECalIncremental;    //A track created by FGD-ECal matching algorithm
   double               Charge;                  //Charge
   double               EDeposit;                //Deposited charge for the object.
   TVector3             Cone;                    //Opening angles of the cone (only for showers)
   double               Width;                   //Width of the shower (perpendicular to the direction)
   double               Length;                  //Length of the track or shower (RMS)
   vector<TLorentzVector> NodePosition;            //Position of each node
   vector<TLorentzVector> HitPosition;             //Position of each hit
   vector<int>            ParticleIds;             //PDG codes obtained in the recon combined PID
   vector<double>         PIDWeights;              //PID likelihoods for combined PID
   TLorentzVector         FrontPosition;           //Front position of the object.
   TLorentzVector         BackPosition;            //Back position of the object
   TVector3               FrontDirection;          //Front direction of the object.
   TVector3               BackDirection;           //Back direction of the object.
   double                 FrontMomentum;           //Front momentum of the object
   double                 FrontCharge;             //Charge of the object at the first state
   double                 BackMomentum;            //Back omentum of the object
   double                 BackCharge;              //Charge of the object at the back state
   double                 FrontMomentumError;      //Error on the momentum of the object
   double                 BackMomentumError;       //Error on the momentum of the object at last state
   double                 FrontStateCov[7][7];     //Full covariance matrix for front state: pos,  dir, qp
   double                 BackStateCov[7][7];      //Full covariance matrix for last state: pos, dir, qp
   double                 RangeMomentumMuon;       //Momentum by range for the muon hypothesis
   double                 RangeMomentumMuonFlip;    //Momentum by range for the flipped muon hypothesis
   double                 RangeMomentumPion;        //Momentum by range for the pion hypothesis
   double                 RangeMomentumPionFlip;    //Momentum by range for the flipped pion hypothesis
   double                 RangeMomentumElectron;    //Momentum by range for the electron hypothesis
   double                 RangeMomentumElectronFlip;    //Momentum by range for the flipped electron hypothesis
   double                 RangeMomentumProton;          //Momentum by range for the proton hypothesis
   double                 RangeMomentumProtonFlip;      //Momentum by range for the flipped proton hypothesis
   double                 RangeMomentumEndToTPCMuon;    //Momentum by range for the muon hypothesis (from end to a TPC)
   double                 RangeMomentumEndToTPCPion;    //Momentum by range for the pion hypothesis (from end to a TPC)
   double                 RangeMomentumEndToTPCElectron;    //Momentum by range for the electron hypothesis (from end to a TPC)
   double                 RangeMomentumEndToTPCProton;      //omentum by range for the proton hypothesis (from end to a TPC)
   vector<pair<unsigned long,TVector2> > NodeTimes;                        //vector of pairs, sub-detecor number and time-stamps of edge nodes in this subdetector
   TLorentzVector                        PositionAtTrueVertex;             //Position at the true vertex.
   TVector3                              DirectionAtTrueVertex;            //Direction at the true vertex.
   double                                MomentumAtTrueVertex;             //Momentum at the true vertex.
   double                                MomentumErrorAtTrueVertex;        //Error of the momentum at the true vertex.
   double                                ChargeAtTrueVertex;               //Charge at the true vertex.
   double                                StateCovAtTrueVertex[7][7];       //Full covariance matrix for the state: pos,  dir, qp at the true vertex.
   int                                   EntranceOK[25];                   //Status of the subdetector entrance.
   int                                   ExitOK[25];                       //Status of the subdetector exit.
   TLorentzVector                        EntrancePosition[25];             //The position of the object at the entrance of each subdetector.
   TLorentzVector                        ExitPosition[25];                 //The position of the object at the exit of each subdetector.
   TVector3                              EntranceDirection[25];            //The direction of the object at the entrance of each subdetector volume.
   TVector3                              ExitDirection[25];                //The direction of the object at the exit of each subdetector.
   double                                EntranceMomentum[25];             //The momentum of the object at the entrance of each subdetector.
   double                                ExitMomentum[25];                 //The momentum of the object at the exit of each subdetector.
   TLorentzVector                        EntrancePositionErr[25];          //The error of the position of the object at the entrance of each subdetector.
   TLorentzVector                        ExitPositionErr[25];              //The error of the position of the object at the exit of each subdetector.
   TVector3                              EntranceDirectionErr[25];         //The error of the direction of the object at the entrance of each subdetector.
   TVector3                              ExitDirectionErr[25];             //The error of the direction of the object at the exit of each subdetector.
   double                                EntranceMomentumErr[25];          //The error of the momentum of the object at the entrance of each subdetector.
   double                                ExitMomentumErr[25];              //The error of the momentum of the object at the exit of each subdetector.
   int                                   NHitsSaved;                       //Number of entries in the HitsSaved array.
   TClonesArray*                         HitsSaved;                        //the two first and two last hits (TGlobalHit).
   ND::TTrueParticle                     TrueParticle;                     //The true particle
   int                                   NTRACKERs;                        //Number of Tracker objects.
   TClonesArray*                         TRACKER;                          //Tracker specific variables.
   int                                   NTPCs;                            //Number of TPC objects.
   TClonesArray*                         TPC;                              //TPC specific variables.
   int                                   NFGDs;                            //Number of FGD objects.
   TClonesArray*                         FGD;                              //FGD specific variables.
   int                                   NHATs;                            //Number of HAT objects.
   TClonesArray*                         HAT;                              //HAT specific variables.
   int                                   NSFGs;                            //Number of SFG objects.
   TClonesArray*                         SFG;                              //SFG specific variables.
   int                                   NTOFs;                            //Number of TOF objects.
   TClonesArray*                         TOF;                              //TOF specific variables.
   int                                   NECALs;                           //Number of ECAL objects.
   int                                   NDsECALs;                         //Number of DsECAL objects.
   int                                   NTrECALs;                         //Number of TrECAL objects.
   TClonesArray*                         ECAL;                             //ECAL specific variables.
   int                                   NP0DECALs;                        //Number of P0DECAL objects.
   TClonesArray*                         P0DECAL;                          //P0DECAL specific variables.
   int                                   NP0Ds;                            //Number of P0D objects.
   TClonesArray*                         P0D;                              //P0D specific variables.
   int                                   NSMRDs;                           //Number of SMRD objects.
   TClonesArray*                         SMRD;                             //SMRD specific variables.
   int                                   NAlternates;                      //Number of entries in the alternate hypotheses list.
   TClonesArray*                         Alternates;                       //List of alternate hypotheses
   vector<pair<unsigned long,unsigned long> > MatchingDets;                     //
   vector<pair<int,int> >                     MatchingIDs;                      //
   vector<pair<int,int> >                     MatchingTrueIDs;                  //
   vector<double>                             MatchingChi2;                     //
   vector<unsigned short>                     MatchingH;                        //
   vector<vector<double> >                    MatchingR;                        //
   vector<int>                                TPCGasPatternIDs;                 //The IDs of the TREx patterns which contributed to the object
   vector<int>                                TPCGasPathIDs;                    //The IDs of the TREx paths which contributed to the object
   vector<int>                                TPCGasJunctionIDs;                //The IDs of the TREx junctions which contributed to the object
   ND::TGlobalReconModule::TTPCObject         hackTPCObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::THATObject         hackHATObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TFGDObject         hackFGDObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TSFGObject         hackSFGObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TTOFObject         hackTOFObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TECALObject        hackECALObject;                   //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TP0DObject         hackP0DObject;                    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TSMRDObject        hackSMRDObject;                   //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TTrackerObject     hackTrackerObject;                //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TGlobalPIDAlternate hackGlobalPIDAlternate;           //This is just here to fool TFile::MakeProject, not a real object.

   TGlobalPID();
   TGlobalPID(TGlobalPID && ) = default;
   TGlobalPID &operator=(const TGlobalPID & );
   TGlobalPID(const TGlobalPID & );
   virtual ~TGlobalPID();

   ClassDef(TGlobalPID,4); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
