//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TSFGReconModule__TSFGHit_h
#define ND__TSFGReconModule__TSFGHit_h
namespace ND {
namespace TSFGReconModule {
class TSFGHit;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TVector3.h"
#include "Riostream.h"
#include <vector>
#include "TLorentzVector.h"

namespace ND {
namespace TSFGReconModule {
class TSFGHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int GeomId;      //Geometry Id of the TSingleHit.
   float        Charge;      //Reconstructed hit charge without attenuation correction from thE corresponding TSingleHit.
   float        Time;        //Reconstructed hit time from the corresponding TSingleHit.
   TVector3     Position;    //Hit position
   int          TrkHitTag;    //Single/multiple track hit tagging Notation: 1 = multiple track hits, 2 = single track hits, 3 = other (xtalk or ghost)
   std::vector<TLorentzVector> HitSegPosition;    //True hit segments inside the cube position (3D + time)
   std::vector<TVector3>       HitSegDirection;    //True hit segments inside the cube  direction (3D)
   std::vector<int>            HitSegTruePDG;      //True particle PDG of the track contributing to the hit segment
   std::vector<float>          HitSegTrueP;        //True momentum of the track contributing to the hit segment
   std::vector<float>          HitSegTrueEdepo;    //True energy loss of the current hit segment

   TSFGHit();
   TSFGHit(TSFGHit && ) = default;
   TSFGHit &operator=(const TSFGHit & );
   TSFGHit(const TSFGHit & );
   virtual ~TSFGHit();

   ClassDef(TSFGHit,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
