//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerReconModule__TTrackOther_h
#define ND__TTrackerReconModule__TTrackOther_h
namespace ND {
namespace TTrackerReconModule {
class TTrackOther;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TClonesArray.h"
#include "TLorentzVector.h"
#include "ND__TTrackerReconModule__TUnusedHit.h"

namespace ND {
namespace TTrackerReconModule {
class TTrackOther : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //The name of the algorithm that created this object.
   int         Detector;         //Detector used (1,2,3 for TPC, or 4,5 for FGD?)
   int         NHits;            //The number of hits.
   TClonesArray* Hits;             //The hits
   double        EDeposit;         //The deposited charge for the object.
   TLorentzVector FrontPosition;    //The position of the track at itsupstream-most end (x,y,z,t) in mm, ns
   TLorentzVector BackPosition;     //The position of the track at itsdownstream-most end     (x,y,z,t) in mm,ns
   ND::TTrackerReconModule::TUnusedHit hackHits;         //This is just here to fool TFile::MakeProject, nota real object.

   TTrackOther();
   TTrackOther(TTrackOther && ) = default;
   TTrackOther &operator=(const TTrackOther & );
   TTrackOther(const TTrackOther & );
   virtual ~TTrackOther();

   ClassDef(TTrackOther,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
