//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TGlobalVertex_h
#define ND__TGlobalReconModule__TGlobalVertex_h
namespace ND {
namespace TGlobalReconModule {
class TGlobalVertex;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"
#include "TClonesArray.h"
#include "ND__TTrueVertex.h"
#include "ND__TGlobalReconModule__TVertexConstituent.h"

namespace ND {
namespace TGlobalReconModule {
class TGlobalVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         Type;        //Vertex type (0: Global vertex | 1: SFG vertex)
   int         PrimaryIndex;    //The index of the corresponding primary vertex
   string      AlgorithmName;    //The name of the algorithm that created this object.
   int         Status;           //The status for the fit.
   double      Quality;          //The quality of the fit.
   int         NDOF;             //The number of degrees of freedom.
   TLorentzVector Position;         //The position of the vertex.
   TLorentzVector Variance;         //The position variance;
   int            NTrueVertices;    //The true vertex
   TClonesArray*  TrueVertices;     //The true vertex
   int            NConstituents;    //Constituent tracks
   TClonesArray*  Constituents;     //Constituent tracks
   ND::TTrueVertex hackTrueVertexObject;    //This is just here to fool TFile::MakeProject, not a real object.
   ND::TGlobalReconModule::TVertexConstituent hackVertexConstituentObject;    //This is just here to fool TFile::MakeProject, not a real object.

   TGlobalVertex();
   TGlobalVertex(TGlobalVertex && ) = default;
   TGlobalVertex &operator=(const TGlobalVertex & );
   TGlobalVertex(const TGlobalVertex & );
   virtual ~TGlobalVertex();

   ClassDef(TGlobalVertex,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
