//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTRExReconModule__TTPCAnaPattern_h
#define ND__TTRExReconModule__TTPCAnaPattern_h
namespace ND {
namespace TTRExReconModule {
class TTPCAnaPattern;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "TClonesArray.h"

namespace ND {
namespace TTRExReconModule {
class TTPCAnaPattern : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        S1Sflag;     //A flag to say whether this pattern would pass the TPC gas Stage 1 Selection
   int         PatternID;    //The ID of the pattern
   int         NJunctions;    //The number of junctions in the pattern.
   TClonesArray* Junctions;     //The constituent junctions of the pattern
   int           NPaths;        //The number of paths.
   TClonesArray* Paths;         //The constituent paths of the pattern.
   int           TPC;           //The TPC in which the pattern resides.

   TTPCAnaPattern();
   TTPCAnaPattern(TTPCAnaPattern && ) = default;
   TTPCAnaPattern &operator=(const TTPCAnaPattern & );
   TTPCAnaPattern(const TTPCAnaPattern & );
   virtual ~TTPCAnaPattern();

   ClassDef(TTPCAnaPattern,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
