//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrueParticle_h
#define ND__TTrueParticle_h
namespace ND {
class TTrueParticle;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "ND__TTrueVertex.h"

namespace ND {
class TTrueParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         ID;          //G4 Trajectory Id.
   double      Pur;         //The purity for matching the rec particle with the true particle.
   double      Eff;         //The efficiency for matching the rec particle with the true particle.
   ND::TTrueVertex Vertex;      //True vertex associated to this TrueParticle.

   TTrueParticle();
   TTrueParticle(TTrueParticle && ) = default;
   TTrueParticle &operator=(const TTrueParticle & );
   TTrueParticle(const TTrueParticle & );
   virtual ~TTrueParticle();

   ClassDef(TTrueParticle,2); // Generated by MakeProject.
};
} // namespace
#endif
