//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TDatum_h
#define ND__TDatum_h
namespace ND {
class TDatum;
} // end of namespace.

#include "Rtypes.h"
#include "TNamed.h"
#include "ND__TDatum.h"

namespace ND {
class TDatum : public TNamed {

public:
// Nested classes declaration.

public:
// Data Members.
   ND::TDatum* fParent;     //

   TDatum();
   TDatum(TDatum && ) = default;
   TDatum &operator=(const TDatum & );
   TDatum(const TDatum & );
   virtual ~TDatum();

   ClassDef(TDatum,3); // Generated by MakeProject.
};
} // namespace
#endif
