//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TTOFReconModule__TTOFAlgoRes_h
#define ND__TTOFReconModule__TTOFAlgoRes_h
namespace ND {
namespace TTOFReconModule {
class TTOFAlgoRes;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include <vector>

namespace ND {
namespace TTOFReconModule {
class TTOFAlgoRes : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   string      AlgorithmName;    //
   short       Cycle;            //The cycle number, based on the first hit.
   vector<short> Vertices;         //Holds internal Ids of Vertices pertinent to this algorithm result.
   vector<short> Particles;        //Holds internal Ids of Particles pertinent to this algorithm result.
   vector<short> Tracks;           //Holds internal Ids of Tracks pertinent to this algorithm result.
   vector<short> Showers;          //Holds internal Ids of Showers pertinent to this algorithm result.
   vector<short> Clusters;         //Holds internal Ids of Clusters pertinent to this algorithm result.
   vector<short> Nodes;            //Holds internal Ids of Nodes pertinent to this algorithm result.
   vector<short> Hits;             //Holds internal Ids of Hits pertinent to this algorithm result.
   vector<short> SingleHits;       //Holds internal Ids of Hits pertinent to this algorithm result.
   short         NHits;            //A count of the Hits associated with this object.
   unsigned int  UniqueID;         //UNUSED: A unique ID used for reconstruction objects.
   string        FullName;         //The name of the tofRecon algorithm that corresponds to this
   vector<short> AlgoResults;      //Holds internal Ids of daughter algorithm results to this one.
   short         Parent;           //The internal Id of the parent algorithm result of this one.
   short         UsedHitCluster;    //The internal Id of the cluster of hits which were used in a
   short         UnusedHitCluster;    //The internal Id of the cluster of hits which were not used in a

   TTOFAlgoRes();
   TTOFAlgoRes(TTOFAlgoRes && ) = default;
   TTOFAlgoRes &operator=(const TTOFAlgoRes & );
   TTOFAlgoRes(const TTOFAlgoRes & );
   virtual ~TTOFAlgoRes();

   ClassDef(TTOFAlgoRes,6); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
