//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Oct  8 23:09:31 2025 by ROOT version 6.32.02)
//      from the StreamerInfo in file /home/bogdan/Desktop/VScode/nd280/test3/oa_pg_mup_00000001-0001_z5juzaudoyei_anal_000_bsdv01_2.root
//////////////////////////////////////////////////////////


#ifndef ND__TGlobalReconModule__TTrackerObject_h
#define ND__TGlobalReconModule__TTrackerObject_h
namespace ND {
namespace TGlobalReconModule {
class TTrackerObject;
} // end of namespace.
} // end of namespace.

#include "Rtypes.h"
#include "ND__TSubBaseObject.h"

namespace ND {
namespace TGlobalReconModule {
class TTrackerObject : public ND::TSubBaseObject {

public:
// Nested classes declaration.

public:
// Data Members.
   double      Charge;      //
   int         matchingFailure_flag;    //

   TTrackerObject();
   TTrackerObject(TTrackerObject && ) = default;
   TTrackerObject &operator=(const TTrackerObject & );
   TTrackerObject(const TTrackerObject & );
   virtual ~TTrackerObject();

   ClassDef(TTrackerObject,2); // Generated by MakeProject.
};
} // namespace
} // namespace
#endif
